"""
generator.py
------------
Grounded answer generation using Groq's LLM.

Public API
----------
  generate_response(query, retrieved_chunks) -> str

The function:
  1. Filters out weak-match chunks (distance >= DISTANCE_THRESHOLD)
  2. Formats the remaining chunks into a numbered context block
  3. Sends a strictly-grounded system prompt + the context to the LLM
  4. Appends a programmatic source list AFTER generation (not trusted to the LLM)
  5. Returns the final answer string

Grounding is enforced at two levels:
  - System prompt forbids the model from using knowledge outside the context
  - Sources are appended programmatically so they are always accurate,
    regardless of what the model chooses to say
"""

import logging

from groq import Groq

from config import GROQ_API_KEY, LLM_MODEL

log = logging.getLogger(__name__)

_client = Groq(api_key=GROQ_API_KEY)

# Chunks with cosine distance >= this are considered too weak to use.
# Cosine distance ranges 0-2; below 0.6 means the chunk is meaningfully related.
DISTANCE_THRESHOLD = 0.6

# System prompt — grounding is a hard requirement, not a suggestion.
# Key design choices:
#   - "ONLY the CONTEXT below" leaves no room for the model to hedge
#   - The exact fallback phrase is specified so the app can detect it
#   - Source citation is NOT delegated to the model; we append it ourselves
SYSTEM_PROMPT = """\
You are GWU Guide Bot, a helpful assistant for students at George Washington University.

You will be given a set of CONTEXT passages extracted from real Reddit discussions by GWU students.

Rules you must follow — no exceptions:
1. Answer using ONLY information that appears in the CONTEXT passages below.
2. Do NOT use any outside knowledge, even if you are confident it is correct.
3. If the CONTEXT does not contain enough information to answer the question,
   respond with exactly: "I don't have enough information on that topic in my sources."
4. Do NOT invent details, statistics, professor names, building names, or policies
   that are not explicitly stated in the CONTEXT.
5. Keep your answer concise and direct. Quote or closely paraphrase the CONTEXT where possible.
6. Do NOT include a source list — that will be added separately.
"""


def _build_context_block(chunks: list[dict]) -> str:
    """
    Format retrieved chunks into a numbered context block for the prompt.

    Each entry shows the source document name and the chunk text so the model
    can see exactly where each piece of information came from.
    """
    parts = []
    for i, chunk in enumerate(chunks, 1):
        title = chunk.get("doc_title") or chunk.get("doc_name", "Unknown")
        parts.append(f"[{i}] Source: {title}\n{chunk['text'].strip()}")
    return "\n\n---\n\n".join(parts)


def _build_source_list(chunks: list[dict]) -> str:
    """
    Build a deduplicated source list to append AFTER the LLM response.

    Sources are appended programmatically rather than generated by the LLM
    to guarantee accuracy — the model is unreliable at citing sources correctly.
    """
    seen = set()
    lines = []
    for chunk in chunks:
        title = chunk.get("doc_title") or chunk.get("doc_name", "Unknown")
        url   = chunk.get("source_url", "")
        key   = url or title
        if key not in seen:
            seen.add(key)
            line = f"- {title}"
            if url:
                line += f"\n  {url}"
            lines.append(line)
    return "\n".join(lines)


def generate_response(query: str, retrieved_chunks: list[dict]) -> str:
    """
    Generate a grounded answer from retrieved document chunks.

    Parameters
    ----------
    query            : the user's question
    retrieved_chunks : list of dicts from retrieval.retrieve(), each containing:
                         "text", "doc_name", "doc_title", "source_url", "distance"

    Returns
    -------
    A string containing:
      - The grounded answer (from the LLM, constrained to the context)
      - A programmatic source list appended after the LLM response

    Grounding guarantee
    -------------------
    - Chunks with distance >= DISTANCE_THRESHOLD are dropped before the prompt
      is built, so the model never sees off-topic material.
    - The system prompt explicitly forbids using knowledge outside the context.
    - Sources are appended by this function, not generated by the LLM.
    """
    if not retrieved_chunks:
        return (
            "I couldn't find anything relevant to your question in my sources. "
            "Try rephrasing, or your question may be outside the topics I cover."
        )

    # Filter out weak matches — anything >= threshold is too loosely related
    strong_chunks = [c for c in retrieved_chunks if c["distance"] < DISTANCE_THRESHOLD]

    if not strong_chunks:
        return (
            "I don't have enough information on that topic in my sources. "
            f"(Best match had distance {retrieved_chunks[0]['distance']:.3f}, "
            f"threshold is {DISTANCE_THRESHOLD}.)"
        )

    context_block = _build_context_block(strong_chunks)

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {
            "role": "user",
            "content": (
                f"CONTEXT:\n{context_block}\n\n"
                f"QUESTION: {query}"
            ),
        },
    ]

    log.info("Sending query to %s with %d context chunks.", LLM_MODEL, len(strong_chunks))

    resp = _client.chat.completions.create(
        messages=messages,
        model=LLM_MODEL,
        temperature=0.0,   # zero temperature = most deterministic, least hallucination
        max_tokens=512,
    )

    if not (resp.choices and resp.choices[0].message and resp.choices[0].message.content):
        return "The model returned an empty response. Please try again."

    answer = resp.choices[0].message.content.strip()

    # Programmatically append sources — never trust the LLM to cite correctly
    source_list = _build_source_list(strong_chunks)
    final = f"{answer}\n\n**Sources:**\n{source_list}"

    return final


# ── end-to-end smoke test ─────────────────────────────────────────────────────
if __name__ == "__main__":
    import sys
    sys.stdout.reconfigure(encoding="utf-8")
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s  %(levelname)-8s  %(message)s",
        datefmt="%H:%M:%S",
    )

    from retrieval import retrieve

    test_queries = [
        "What do students say about the pacing and rigor of early computer science classes at GWU?",
        "Is the freshman housing lottery actually random, or does placement favor certain preferences?",
        "What are GWU students' favorite study spots on campus?",
    ]

    for query in test_queries:
        print(f"\n{'='*70}")
        print(f"QUERY: {query}")
        print("="*70)
        chunks = retrieve(query)
        response = generate_response(query, chunks)
        print(response)
